Config = {}

Config.DistanceSpawn = 20.0 -- Distance before spawning/despawning the ped. (GTA Units.)
Config.FadeIn = true

Config.barberlocations = {
    [1] = {name = "Valentine", coords = vector3(-307.96, 814.16, 118.99)},
    [2] = {name = "Saint Denis", coords = vector3(2656.16, -1180.87, 53.28)},
    [3] = {name = "Blackwater", coords = vector3(-815.88, -1364.72, 43.75)}
}

Config.Texts = {
    Height = "Height",
    Body = "Body",
    Face = "Face",
    Hair_beard = "Hair & Beard",
	HairStyle = "Hair Style",
	HairColor = "Hair Color",
	BeardStyle = "Beard Style",
	BeardColor = "Beard Color",
    Makeup = "Makeup",
    Appearance = "Appearance",
    Slim = "Slim",
    Sporty = "Sporty",
    Medium = "Medium",
    Fat = "Fat",
    Strong = "Strong",
    FaceWidth = "Face Width",
    SkinTone = "Skin Tone",
    Eyes = "Eyes",
    Eyelids = "Eyelids",
	Eyebrows = "Eyebrows",
    Nose = "Nose",
    Mouth = "Mouth",
    Cheekbones = "Cheek Bones",
    Jaw = "Jaw",
    Ears = "Ears",
	Chin = "Chin",
    Defects = "Defects",
	Hair = "Hair",
	Beard = "Beard",
    Eyelids = "Eyelids",
	Type = "Type",
    Visibility = "Visibility",
	ColorPalette = "Color Palette ",
	ColorFirstrate = "Color First-rate",
    Eyebrow = "Eyebrows",
    NoseCurvature = "Nose Curvature",
    Nose = "Nose",
    UP_DOWN = "UP / DOWN",
    left_right = "left / right",
    UpperLipHeight = "Upper Lip Height",
    UpperLipWidth = "Upper Lip Width",
    UpperLipDepth = "Upper Lip Depth",
    LowerLipHeight = "Lower Lip Height",
    LowerLipWidth = "Lower Lip Width",
    LowerLipDepth = "Lower Lip Depth",
    Mouth = "Mouth",
    Jaw = "Jaw",
    Ears = "Ears",
    Chin = "Chin",
    Make_up = "Make-up",
    Older = "Older",
    Scars = "Type Scars",
	Freckles = "Type Freckles",
    Moles = "Moles",
    Disadvantages = "Disadvantages",
    Spots = "Spots",
    Shadow = "Shadow",
    ColorShadow = "Color Shadow",
    ColorFirst_Class = "Color First-Class Delusion",
    Blushing_Cheek = "Blushing Cheek",
	blush_id = "Cheek Blush Color",
    blush_c1 = "Color First Degree Cheek Redness",
    Lipstick = "Type Lipstick",
    ColorLipstick = "Color Lipstick",
    lipsticks_c1 = "First-Class Color Lipstick",
	lipsticks_c2 = "Second Color Lipstick",
    Eyeliners = "Eyeliners",
    eyeliners_id = "Color Eyeliners",
	eyeliners_c1 = "Color main Eyeliners",
    save = "Save",
    Options = "Options",
    align = "top-left",
	Style = "Style ",
	Color = "Color ",
    Size = "Size",
    Width = "Width ",
    Height = "Height",
	Depth = "Depth",
    Waist = "Waist",
    Distance = "Distance",
    Angle = "Angle",
    Clarity = "Clarity",
    Color1 ="<img src='nui://qr-appearance/img/skin1.png' height='20'>",
    Color2 = "<img src='nui://qr-appearance/img/skin2.png' height='20'>",
    Color3 = "<img src='nui://qr-appearance/img/skin3.png' height='20'>",
    Color4 = "<img src='nui://qr-appearance/img/skin4.png' height='20'>",
    Color5 = "<img src='nui://qr-appearance/img/skin5.png' height='20'>",
    Color6 = "<img src='nui://qr-appearance/img/skin6.png' height='20'>",
    Color7 = "<img src='nui://qr-appearance/img/skin7.png' height='20'>",
}

Config.BarberNpc = {

	[1] = { ["Model"] = "s_m_m_barber_01",	["Pos"] = vector3(-307.96, 814.16, 118.99),		["Heading"] = 190.93}, -- Thieve's Landing 
	[2] = { ["Model"] = "s_m_m_barber_01",	["Pos"] = vector3(2656.16, -1180.87, 53.28),		["Heading"] = 176.33}, -- Saint Denis 
    [3] = { ["Model"] = "s_m_m_barber_01",	["Pos"] = vector3(-815.88, -1364.72, 43.75),		["Heading"] = 268.01}, -- Saint Denis 

	
}